#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --newmode "1440x900_60.00"  106.50  1440 1528 1672 1904  900 903 909 934 -hsync +vsync &
xrandr --addmode VGA-1-1 1440x900_60.00 &
xrandr --output DVI-0 --auto --output VGA-1-1 --mode 1440x900_60.00 --left-of DVI-0 &

bspc monitor DVI-0 -d 2 3 4 5 6 7 8 9 10
bspc monitor VGA-1-1 -d 1

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Google-chrome desktop='^2'
bspc rule -a icq desktop='^3' follow=on
bspc rule -a observer.exe desktop='^5' follow=on
bspc rule -a org.remmina.Remmina desktop='^1'
bspc rule -a Alacritty desktop='^10' follow=on
bspc rule -a TelegramDesktop desktop='^9' follow=on
bspc rule -a spotify desktop='^8' follow=on

exec xsetroot -cursor_name left_ptr &
killall sxhkd &
exec sxhkd -c $HOME/.config/bspwm/sxhkd/sxhkdrc &
exec $HOME/.config/polybar/launch.sh &
exec nitrogen --restore &
exec picom -m ~/.config/picom.conf &
exec setxkbmap -model pc104 -layout us,ru -option grp:alt_shift_toggle &
#exec alacritty
