#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a TelegramDesktop desktop='^10' follow=on
bspc rule -a Spotify desktop='^9' follow=on

exec xsetroot -cursor_name left_ptr &
exec sxhkd -c $HOME/.config/bspwm/sxhkd/sxhkdrc &
exec $HOME/.config/polybar/launch.sh &
exec nitrogen --restore &
exec $HOME/.local/bin/picom -b --animations --animation-for-open-window zoom --animation-stiffness 750 --animation-window-mass 0.5 &
exec setxkbmap -model pc104 -layout us,ru -option grp:alt_shift_toggle &

